### ISSUE TITLE
レンジデータを表示できない

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/choreonoid_ros_pkg#11]
rvizでレンジデータを表示しようとすると、次のような警告がでます。どうすればよいのでしょうか？

```
[ WARN] [1446025707.493125293]: Invalid argument passed to canTransform argument source_frame in tf2 frame_ids cannot be empty
```

**Comment by yosuke** [comment]
rvizでレンジデータを表示するにはtfという関節＆リンクをツリー構造にしたデータを構築する必要があります（順運動学をたどったうえで画面に表示される）。
この部分、launchfileできれいに書きたいと思いますので、もう少々お待ちください。

**Comment by yosuke** [comment]
rvizで表示する環境とtfの構築は完了しました。

joint_stateについては問題なくpublishできていることがrvizの画面から確認できました。

あとは各センサーデータのヘッダ部分にモデルのリンク情報を設定する必要があります（以下メモです）。

カメラは
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_plugins/src/gazebo_ros_camera_utils.cpp#L578

RGBDは
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_plugins/src/gazebo_ros_camera_utils.cpp#L578

レンジは
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_plugins/src/gazebo_ros_camera_utils.cpp#L578

imuは
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_plugins/src/gazebo_ros_camera_utils.cpp#L578

**Comment by yosuke** [comment]
現状ここまで来ています。レーザースキャンデータにintensityという項目があり、おそらくそこに適切なデータを入れればスキャンデータも表示できると思うのですが、まだ値がよくわかっていません。

![screenshot from 2015-11-02 18 10 47](https://cloud.githubusercontent.com/assets/18067/10877841/2bb76f62-818d-11e5-812a-83acf1d855cc.png)

**Comment by yosuke** [comment]
スキャンデータについても表示できるようになりました。RGBDの方もチェックします。

![screenshot from 2015-11-04 08 55 37](https://cloud.githubusercontent.com/assets/18067/10925479/d9d116c6-82d1-11e5-944e-f84503df9a58.png)

**Comment by yosuke** [comment]
RGBDについても表示されました（間違えていた部分があったのでデバッグしました）。

![screenshot from 2015-11-04 16 46 08](https://cloud.githubusercontent.com/assets/18067/10932383/99afb808-8313-11e5-84f3-7e94742a0f13.png)
