### ISSUE TITLE
関節情報のパブリッシュ (/[robot name]/[control name]/joint_states) 周期が正しくない

### ISSUE THREAD

**Issue by hmatsushita** [fkanehiro/choreonoid_ros_pkg#57]
Update rate の設定を 100.0 ms に設定した場合、100.0 ms 周期でなく 10.0 ms 周期で関節情報のパブリッシュが実施されています。

**Comment by fkanehiro** [comment]
Update rateは[Hz]だとおもいますので、100[Hz]であれば10[ms]周期で正しいのではないでしょうか。
https://github.com/fkanehiro/choreonoid_ros_pkg/blob/master/choreonoid_plugins/src/BodyRosJointControllerItem.cpp#L121

本題とはズレますが、JointStateはセンサ情報であって、関節制御とは関係がないので、そのUpdate Rateの設定がBodyRosJointControllerItemにあるというのは変ではないでしょうか？

**Comment by hmatsushita** [comment]
情報ありがとうございます。
本 issue を取り下げます。

JointState につきましては、別 issue として上げます。
