### ISSUE TITLE
関節軌道データの実行契機に誤りがあります

### ISSUE THREAD

**Issue by hmatsushita** [fkanehiro/choreonoid_ros_pkg#59]
次の軌道データ (trajectory_msgs/JointTrajectoryPoint[]) の実行時間 (実行契機) の計算の際、timestamp + 次のインデックスの duration となるべき所が、timestamp + 現在のインデックスの duration となっています。

**Comment by fkanehiro** [comment]
こちらも正解はどうあるべきかというドキュメントはどこかにありますでしょうか？

**Comment by hmatsushita** [comment]
#58 と同様にサンプル等を含め正式な仕様の確認をいたします。
少々お時間をください。

**Comment by hmatsushita** [comment]
#58 のコメントに記載いたしましたが、timestamp + duration が指定関節角度の目標時間となりますので、次の軌道データの目標時間は、timestamp + 次のインデックスの duration となると考えます。

**Comment by hmatsushita** [comment]
https://github.com/fkanehiro/choreonoid_ros_pkg/blob/master/choreonoid_plugins/src/BodyRosJointControllerItem.cpp#L185-L188 が問題の箇所となります。

**Comment by hmatsushita** [comment]
9ae6cba で修正を確認しました。
