### ISSUE TITLE
/clock トピックのパブリッシュ周期が一定ではない

### ISSUE THREAD

**Issue by hmatsushita** [fkanehiro/choreonoid_ros_pkg#60]
不具合か仕様かは分かりませんが、/clock トピックのパブリッシュ周期が 1 〜 30 ms 程度とばらつきのある周期で提供されています。

**Comment by fkanehiro** [comment]
この1〜30msというのはシミュレーション世界での時間でしょうか？それとも実世界での時間でしょうか？

**Comment by hmatsushita** [comment]
シミュレーション世界の時間となります。

**Comment by fkanehiro** [comment]
TimeBarからのシグナルで出していることが原因ですね。
https://github.com/fkanehiro/choreonoid_ros_pkg/blob/master/choreonoid_plugins/src/WorldRosItem.cpp#L75
そもそもタイムバーはシミュレーション中にユーザ操作で遡ったりすることも可能なので、これはいけないですね。
Gazeboではシミュレーションの時間刻み毎に出しているのではないかと思いますが、確認して合わせるようにお願いします。

**Comment by hmatsushita** [comment]
承知しました。
Gazebo に合せた対応を取るようにいたします。
